#!/usr/bin/env python3
"""Generate a packed NFKD decomposition table for the Supertonic C++ pipeline.

Supertonic's text preprocessing applies Unicode NFKD normalization before
mapping characters to indices (see supertonic_torch/pipeline.py). The trained
``unicode_indexer`` only knows NFKD-normal-form characters (base letters +
combining marks), not precomposed ones (e.g. 'é' is unsupported, but 'e' +
U+0301 are). This script emits a header with every BMP codepoint whose NFKD
form differs from itself, so the C++ code can reproduce Python's
``unicodedata.normalize("NFKD", ...)`` for real (BMP) text.

Applied per-codepoint then concatenated — equivalent to full-string NFKD for
the practical case of precomposed letters (each decomposes independently and
its combining marks are already canonically ordered).

Usage:
    python scripts/gen_nfkd_table.py > \
        ../common/rnexecutorch/models/text_to_speech/supertonic/NfkdTable.h
"""

import sys
import unicodedata

HEADER = """// AUTO-GENERATED by scripts/gen_nfkd_table.py — DO NOT EDIT BY HAND.
// Packed Unicode NFKD decomposition table for BMP codepoints whose NFKD form
// differs from themselves. See gen_nfkd_table.py for details.
#pragma once

#include <cstddef>
#include <cstdint>

namespace rnexecutorch::models::text_to_speech::supertonic::nfkd {

struct NfkdEntry {
  char32_t src;    // source codepoint
  uint32_t offset; // offset into kNfkdData
  uint16_t len;    // number of codepoints in the decomposition
};

"""

FOOTER = """
} // namespace rnexecutorch::models::text_to_speech::supertonic::nfkd
"""


def main() -> None:
    entries = []  # (src, decomposition list[int])
    for cp in range(0x10000):
        if 0xD800 <= cp <= 0xDFFF:  # surrogates
            continue
        ch = chr(cp)
        d = unicodedata.normalize("NFKD", ch)
        if d != ch:
            entries.append((cp, [ord(c) for c in d]))

    data = []
    packed = []
    for src, decomp in entries:
        offset = len(data)
        data.extend(decomp)
        packed.append((src, offset, len(decomp)))

    out = [HEADER]
    out.append(f"inline constexpr std::size_t kNfkdEntryCount = {len(packed)};")
    out.append(f"inline constexpr std::size_t kNfkdDataSize = {len(data)};\n")

    # flat decomposition data
    out.append("inline constexpr char32_t kNfkdData[kNfkdDataSize] = {")
    for i in range(0, len(data), 16):
        out.append("    " + ",".join(f"0x{c:X}" for c in data[i : i + 16]) + ",")
    out.append("};\n")

    # sorted-by-src entries for binary search
    out.append("inline constexpr NfkdEntry kNfkdEntries[kNfkdEntryCount] = {")
    for src, offset, length in packed:  # already ascending in src
        out.append(f"    {{0x{src:X}, {offset}, {length}}},")
    out.append("};")

    out.append(FOOTER)
    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
