const createHFRecognizerDownloadUrl = (alphabet: string, size: number) => {
  return `https://huggingface.co/software-mansion/react-native-executorch-recognizer-crnn.en/resolve/v0.4.0/xnnpack/${alphabet}/xnnpack_crnn_${alphabet}_${size}.pte`;
};
export const RECOGNIZER_ENGLISH_CRNN_512 = createHFRecognizerDownloadUrl(
  'english',
  512
);
export const RECOGNIZER_ENGLISH_CRNN_256 = createHFRecognizerDownloadUrl(
  'english',
  256
);
export const RECOGNIZER_ENGLISH_CRNN_128 = createHFRecognizerDownloadUrl(
  'english',
  128
);
export const RECOGNIZER_ENGLISH_CRNN_64 = createHFRecognizerDownloadUrl(
  'english',
  64
);

export const RECOGNIZER_LATIN_CRNN_512 = createHFRecognizerDownloadUrl(
  'latin',
  512
);
export const RECOGNIZER_LATIN_CRNN_256 = createHFRecognizerDownloadUrl(
  'latin',
  256
);
export const RECOGNIZER_LATIN_CRNN_128 = createHFRecognizerDownloadUrl(
  'latin',
  128
);
export const RECOGNIZER_LATIN_CRNN_64 = createHFRecognizerDownloadUrl(
  'latin',
  64
);

export const RECOGNIZER_JAPANESE_CRNN_512 = createHFRecognizerDownloadUrl(
  'japanese',
  512
);
export const RECOGNIZER_JAPANESE_CRNN_256 = createHFRecognizerDownloadUrl(
  'japanese',
  256
);
export const RECOGNIZER_JAPANESE_CRNN_128 = createHFRecognizerDownloadUrl(
  'japanese',
  128
);
export const RECOGNIZER_JAPANESE_CRNN_64 = createHFRecognizerDownloadUrl(
  'japanese',
  64
);

export const RECOGNIZER_KANNADA_CRNN_512 = createHFRecognizerDownloadUrl(
  'kannada',
  512
);
export const RECOGNIZER_KANNADA_CRNN_256 = createHFRecognizerDownloadUrl(
  'kannada',
  256
);
export const RECOGNIZER_KANNADA_CRNN_128 = createHFRecognizerDownloadUrl(
  'kannada',
  128
);
export const RECOGNIZER_KANNADA_CRNN_64 = createHFRecognizerDownloadUrl(
  'kannada',
  64
);

export const RECOGNIZER_KOREAN_CRNN_512 = createHFRecognizerDownloadUrl(
  'korean',
  512
);
export const RECOGNIZER_KOREAN_CRNN_256 = createHFRecognizerDownloadUrl(
  'korean',
  256
);
export const RECOGNIZER_KOREAN_CRNN_128 = createHFRecognizerDownloadUrl(
  'korean',
  128
);
export const RECOGNIZER_KOREAN_CRNN_64 = createHFRecognizerDownloadUrl(
  'korean',
  64
);

export const RECOGNIZER_TELUGU_CRNN_512 = createHFRecognizerDownloadUrl(
  'telugu',
  512
);
export const RECOGNIZER_TELUGU_CRNN_256 = createHFRecognizerDownloadUrl(
  'telugu',
  256
);
export const RECOGNIZER_TELUGU_CRNN_128 = createHFRecognizerDownloadUrl(
  'telugu',
  128
);
export const RECOGNIZER_TELUGU_CRNN_64 = createHFRecognizerDownloadUrl(
  'telugu',
  64
);

export const RECOGNIZER_ZH_SIM_CRNN_512 = createHFRecognizerDownloadUrl(
  'zh-sim',
  512
);
export const RECOGNIZER_ZH_SIM_CRNN_256 = createHFRecognizerDownloadUrl(
  'zh-sim',
  256
);
export const RECOGNIZER_ZH_SIM_CRNN_128 = createHFRecognizerDownloadUrl(
  'zh-sim',
  128
);
export const RECOGNIZER_ZH_SIM_CRNN_64 = createHFRecognizerDownloadUrl(
  'zh-sim',
  64
);

export const RECOGNIZER_CYRILLIC_CRNN_512 = createHFRecognizerDownloadUrl(
  'cyrillic',
  512
);
export const RECOGNIZER_CYRILLIC_CRNN_256 = createHFRecognizerDownloadUrl(
  'cyrillic',
  256
);
export const RECOGNIZER_CYRILLIC_CRNN_128 = createHFRecognizerDownloadUrl(
  'cyrillic',
  128
);
export const RECOGNIZER_CYRILLIC_CRNN_64 = createHFRecognizerDownloadUrl(
  'cyrillic',
  64
);

export const RECOGNIZER_ABQ_CRNN_512 = RECOGNIZER_CYRILLIC_CRNN_512;
export const RECOGNIZER_ABQ_CRNN_256 = RECOGNIZER_CYRILLIC_CRNN_256;
export const RECOGNIZER_ABQ_CRNN_128 = RECOGNIZER_CYRILLIC_CRNN_128;
export const RECOGNIZER_ABQ_CRNN_64 = RECOGNIZER_CYRILLIC_CRNN_64;

export const RECOGNIZER_ADY_CRNN_512 = RECOGNIZER_CYRILLIC_CRNN_512;
export const RECOGNIZER_ADY_CRNN_256 = RECOGNIZER_CYRILLIC_CRNN_256;
export const RECOGNIZER_ADY_CRNN_128 = RECOGNIZER_CYRILLIC_CRNN_128;
export const RECOGNIZER_ADY_CRNN_64 = RECOGNIZER_CYRILLIC_CRNN_64;

export const RECOGNIZER_AF_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_AF_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_AF_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_AF_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_AVA_CRNN_512 = RECOGNIZER_CYRILLIC_CRNN_512;
export const RECOGNIZER_AVA_CRNN_256 = RECOGNIZER_CYRILLIC_CRNN_256;
export const RECOGNIZER_AVA_CRNN_128 = RECOGNIZER_CYRILLIC_CRNN_128;
export const RECOGNIZER_AVA_CRNN_64 = RECOGNIZER_CYRILLIC_CRNN_64;

export const RECOGNIZER_AZ_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_AZ_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_AZ_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_AZ_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_BE_CRNN_512 = RECOGNIZER_CYRILLIC_CRNN_512;
export const RECOGNIZER_BE_CRNN_256 = RECOGNIZER_CYRILLIC_CRNN_256;
export const RECOGNIZER_BE_CRNN_128 = RECOGNIZER_CYRILLIC_CRNN_128;
export const RECOGNIZER_BE_CRNN_64 = RECOGNIZER_CYRILLIC_CRNN_64;

export const RECOGNIZER_BG_CRNN_512 = RECOGNIZER_CYRILLIC_CRNN_512;
export const RECOGNIZER_BG_CRNN_256 = RECOGNIZER_CYRILLIC_CRNN_256;
export const RECOGNIZER_BG_CRNN_128 = RECOGNIZER_CYRILLIC_CRNN_128;
export const RECOGNIZER_BG_CRNN_64 = RECOGNIZER_CYRILLIC_CRNN_64;

export const RECOGNIZER_BS_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_BS_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_BS_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_BS_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_CH_SIM_CRNN_512 = RECOGNIZER_ZH_SIM_CRNN_512;
export const RECOGNIZER_CH_SIM_CRNN_256 = RECOGNIZER_ZH_SIM_CRNN_256;
export const RECOGNIZER_CH_SIM_CRNN_128 = RECOGNIZER_ZH_SIM_CRNN_128;
export const RECOGNIZER_CH_SIM_CRNN_64 = RECOGNIZER_ZH_SIM_CRNN_64;

export const RECOGNIZER_CHE_CRNN_512 = RECOGNIZER_CYRILLIC_CRNN_512;
export const RECOGNIZER_CHE_CRNN_256 = RECOGNIZER_CYRILLIC_CRNN_256;
export const RECOGNIZER_CHE_CRNN_128 = RECOGNIZER_CYRILLIC_CRNN_128;
export const RECOGNIZER_CHE_CRNN_64 = RECOGNIZER_CYRILLIC_CRNN_64;

export const RECOGNIZER_CS_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_CS_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_CS_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_CS_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_CY_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_CY_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_CY_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_CY_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_DA_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_DA_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_DA_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_DA_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_DAR_CRNN_512 = RECOGNIZER_CYRILLIC_CRNN_512;
export const RECOGNIZER_DAR_CRNN_256 = RECOGNIZER_CYRILLIC_CRNN_256;
export const RECOGNIZER_DAR_CRNN_128 = RECOGNIZER_CYRILLIC_CRNN_128;
export const RECOGNIZER_DAR_CRNN_64 = RECOGNIZER_CYRILLIC_CRNN_64;

export const RECOGNIZER_DE_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_DE_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_DE_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_DE_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_EN_CRNN_512 = RECOGNIZER_ENGLISH_CRNN_512;
export const RECOGNIZER_EN_CRNN_256 = RECOGNIZER_ENGLISH_CRNN_256;
export const RECOGNIZER_EN_CRNN_128 = RECOGNIZER_ENGLISH_CRNN_128;
export const RECOGNIZER_EN_CRNN_64 = RECOGNIZER_ENGLISH_CRNN_64;

export const RECOGNIZER_ES_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_ES_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_ES_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_ES_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_ET_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_ET_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_ET_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_ET_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_FR_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_FR_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_FR_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_FR_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_GA_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_GA_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_GA_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_GA_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_HR_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_HR_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_HR_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_HR_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_HU_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_HU_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_HU_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_HU_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_ID_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_ID_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_ID_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_ID_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_INH_CRNN_512 = RECOGNIZER_CYRILLIC_CRNN_512;
export const RECOGNIZER_INH_CRNN_256 = RECOGNIZER_CYRILLIC_CRNN_256;
export const RECOGNIZER_INH_CRNN_128 = RECOGNIZER_CYRILLIC_CRNN_128;
export const RECOGNIZER_INH_CRNN_64 = RECOGNIZER_CYRILLIC_CRNN_64;

export const RECOGNIZER_IC_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_IC_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_IC_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_IC_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_IT_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_IT_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_IT_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_IT_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_JA_CRNN_512 = RECOGNIZER_JAPANESE_CRNN_512;
export const RECOGNIZER_JA_CRNN_256 = RECOGNIZER_JAPANESE_CRNN_256;
export const RECOGNIZER_JA_CRNN_128 = RECOGNIZER_JAPANESE_CRNN_128;
export const RECOGNIZER_JA_CRNN_64 = RECOGNIZER_JAPANESE_CRNN_64;

export const RECOGNIZER_KBD_CRNN_512 = RECOGNIZER_CYRILLIC_CRNN_512;
export const RECOGNIZER_KBD_CRNN_256 = RECOGNIZER_CYRILLIC_CRNN_256;
export const RECOGNIZER_KBD_CRNN_128 = RECOGNIZER_CYRILLIC_CRNN_128;
export const RECOGNIZER_KBD_CRNN_64 = RECOGNIZER_CYRILLIC_CRNN_64;

export const RECOGNIZER_KN_CRNN_512 = RECOGNIZER_KANNADA_CRNN_512;
export const RECOGNIZER_KN_CRNN_256 = RECOGNIZER_KANNADA_CRNN_256;
export const RECOGNIZER_KN_CRNN_128 = RECOGNIZER_KANNADA_CRNN_128;
export const RECOGNIZER_KN_CRNN_64 = RECOGNIZER_KANNADA_CRNN_64;

export const RECOGNIZER_KO_CRNN_512 = RECOGNIZER_KOREAN_CRNN_512;
export const RECOGNIZER_KO_CRNN_256 = RECOGNIZER_KOREAN_CRNN_256;
export const RECOGNIZER_KO_CRNN_128 = RECOGNIZER_KOREAN_CRNN_128;
export const RECOGNIZER_KO_CRNN_64 = RECOGNIZER_KOREAN_CRNN_64;

export const RECOGNIZER_KU_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_KU_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_KU_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_KU_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_LA_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_LA_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_LA_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_LA_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_LBE_CRNN_512 = RECOGNIZER_CYRILLIC_CRNN_512;
export const RECOGNIZER_LBE_CRNN_256 = RECOGNIZER_CYRILLIC_CRNN_256;
export const RECOGNIZER_LBE_CRNN_128 = RECOGNIZER_CYRILLIC_CRNN_128;
export const RECOGNIZER_LBE_CRNN_64 = RECOGNIZER_CYRILLIC_CRNN_64;

export const RECOGNIZER_LEZ_CRNN_512 = RECOGNIZER_CYRILLIC_CRNN_512;
export const RECOGNIZER_LEZ_CRNN_256 = RECOGNIZER_CYRILLIC_CRNN_256;
export const RECOGNIZER_LEZ_CRNN_128 = RECOGNIZER_CYRILLIC_CRNN_128;
export const RECOGNIZER_LEZ_CRNN_64 = RECOGNIZER_CYRILLIC_CRNN_64;

export const RECOGNIZER_LT_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_LT_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_LT_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_LT_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_LV_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_LV_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_LV_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_LV_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_MI_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_MI_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_MI_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_MI_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_MN_CRNN_512 = RECOGNIZER_CYRILLIC_CRNN_512;
export const RECOGNIZER_MN_CRNN_256 = RECOGNIZER_CYRILLIC_CRNN_256;
export const RECOGNIZER_MN_CRNN_128 = RECOGNIZER_CYRILLIC_CRNN_128;
export const RECOGNIZER_MN_CRNN_64 = RECOGNIZER_CYRILLIC_CRNN_64;

export const RECOGNIZER_MS_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_MS_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_MS_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_MS_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_MT_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_MT_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_MT_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_MT_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_NL_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_NL_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_NL_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_NL_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_NO_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_NO_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_NO_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_NO_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_OC_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_OC_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_OC_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_OC_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_PI_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_PI_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_PI_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_PI_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_PL_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_PL_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_PL_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_PL_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_PT_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_PT_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_PT_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_PT_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_RO_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_RO_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_RO_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_RO_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_RU_CRNN_512 = RECOGNIZER_CYRILLIC_CRNN_512;
export const RECOGNIZER_RU_CRNN_256 = RECOGNIZER_CYRILLIC_CRNN_256;
export const RECOGNIZER_RU_CRNN_128 = RECOGNIZER_CYRILLIC_CRNN_128;
export const RECOGNIZER_RU_CRNN_64 = RECOGNIZER_CYRILLIC_CRNN_64;

export const RECOGNIZER_RS_CYRILLIC_CRNN_512 = RECOGNIZER_CYRILLIC_CRNN_512;
export const RECOGNIZER_RS_CYRILLIC_CRNN_256 = RECOGNIZER_CYRILLIC_CRNN_256;
export const RECOGNIZER_RS_CYRILLIC_CRNN_128 = RECOGNIZER_CYRILLIC_CRNN_128;
export const RECOGNIZER_RS_CYRILLIC_CRNN_64 = RECOGNIZER_CYRILLIC_CRNN_64;

export const RECOGNIZER_RS_LATIN_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_RS_LATIN_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_RS_LATIN_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_RS_LATIN_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_SK_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_SK_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_SK_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_SK_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_SL_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_SL_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_SL_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_SL_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_SQ_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_SQ_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_SQ_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_SQ_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_SV_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_SV_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_SV_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_SV_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_SW_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_SW_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_SW_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_SW_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_TAB_CRNN_512 = RECOGNIZER_CYRILLIC_CRNN_512;
export const RECOGNIZER_TAB_CRNN_256 = RECOGNIZER_CYRILLIC_CRNN_256;
export const RECOGNIZER_TAB_CRNN_128 = RECOGNIZER_CYRILLIC_CRNN_128;
export const RECOGNIZER_TAB_CRNN_64 = RECOGNIZER_CYRILLIC_CRNN_64;

export const RECOGNIZER_TE_CRNN_512 = RECOGNIZER_TELUGU_CRNN_512;
export const RECOGNIZER_TE_CRNN_256 = RECOGNIZER_TELUGU_CRNN_256;
export const RECOGNIZER_TE_CRNN_128 = RECOGNIZER_TELUGU_CRNN_128;
export const RECOGNIZER_TE_CRNN_64 = RECOGNIZER_TELUGU_CRNN_64;

export const RECOGNIZER_TJK_CRNN_512 = RECOGNIZER_CYRILLIC_CRNN_512;
export const RECOGNIZER_TJK_CRNN_256 = RECOGNIZER_CYRILLIC_CRNN_256;
export const RECOGNIZER_TJK_CRNN_128 = RECOGNIZER_CYRILLIC_CRNN_128;
export const RECOGNIZER_TJK_CRNN_64 = RECOGNIZER_CYRILLIC_CRNN_64;

export const RECOGNIZER_TL_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_TL_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_TL_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_TL_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_TR_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_TR_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_TR_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_TR_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_UK_CRNN_512 = RECOGNIZER_CYRILLIC_CRNN_512;
export const RECOGNIZER_UK_CRNN_256 = RECOGNIZER_CYRILLIC_CRNN_256;
export const RECOGNIZER_UK_CRNN_128 = RECOGNIZER_CYRILLIC_CRNN_128;
export const RECOGNIZER_UK_CRNN_64 = RECOGNIZER_CYRILLIC_CRNN_64;

export const RECOGNIZER_UZ_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_UZ_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_UZ_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_UZ_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;

export const RECOGNIZER_VI_CRNN_512 = RECOGNIZER_LATIN_CRNN_512;
export const RECOGNIZER_VI_CRNN_256 = RECOGNIZER_LATIN_CRNN_256;
export const RECOGNIZER_VI_CRNN_128 = RECOGNIZER_LATIN_CRNN_128;
export const RECOGNIZER_VI_CRNN_64 = RECOGNIZER_LATIN_CRNN_64;
