compressionLevel: mixed

enableGlobalCache: false

logFilters:
  - code: YN0002
    pattern: "react-native-executorch-monorepo@* doesn't provide *"
    level: discard

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.1.1.cjs
