constexpr CGFloat textThreshold = 0.4;
constexpr CGFloat textThresholdVertical = 0.3;
constexpr CGFloat linkThreshold = 0.4;
constexpr CGFloat lowTextThreshold = 0.7;
constexpr CGFloat centerThreshold = 0.5;
constexpr CGFloat distanceThreshold = 2.0;
constexpr CGFloat heightThreshold = 2.0;
constexpr CGFloat restoreRatio = 3.2;
constexpr CGFloat restoreRatioVertical = 2.0;
constexpr CGFloat singleCharacterCenterThreshold = 0.3;
constexpr CGFloat lowConfidenceThreshold = 0.3;
constexpr CGFloat adjustContrast = 0.2;
constexpr int minSideThreshold = 15;
constexpr int maxSideThreshold = 30;
constexpr int recognizerHeight = 64;
constexpr int largeRecognizerWidth = 512;
constexpr int mediumRecognizerWidth = 256;
constexpr int smallRecognizerWidth = 128;
constexpr int smallVerticalRecognizerWidth = 64;
constexpr int maxWidth = largeRecognizerWidth + (largeRecognizerWidth * 0.15);
constexpr int minSize = 20;
constexpr int singleCharacterMinSize = 70;
constexpr int recognizerImageSize = 1280;

const cv::Scalar mean(0.485, 0.456, 0.406);
const cv::Scalar variance(0.229, 0.224, 0.225);