import { Template } from '@huggingface/jinja';

import { tensor, type Tensor } from '../../../core/tensor';
import { RnExecuTorchError } from '../../../core/error';
import type { ImageBuffer } from '../../cv';
import {
  createImagePreprocessor,
  type ImagePreprocessorOptions,
} from '../../cv/tasks/preprocessing';

import type { Modality, Prompt, MediaInput } from '../llmRunner';
import type { ToolDefinition, ToolCall } from './toolCalling';

/**
 * High-level media payload input for chat turns.
 * @category Types
 */
export type ChatMediaInput =
  | { readonly kind: 'image'; readonly image: ImageBuffer }
  | { readonly kind: 'audio'; readonly audio: unknown };

/**
 * Interleaved text and media content for a chat turn.
 * @category Types
 */
export type ChatMessageContent = string | readonly (string | ChatMediaInput)[];

/**
 * Conversation turn representing system, user, assistant, or tool execution messages.
 * @category Types
 */
export type ChatMessage = Readonly<
  | { role: 'system' | 'user'; content: ChatMessageContent }
  | { role: 'assistant'; content?: ChatMessageContent; toolCalls?: readonly ToolCall[] }
  | { role: 'tool'; content: ChatMessageContent; toolCallId?: string; name?: string }
>;

/**
 * Image preprocessing and sentinel token config for vision-language LLMs.
 * @category Types
 */
export type LLMImagePreprocessorConfig = {
  /** Sentinel token delimiters inserted into Jinja prompts. */
  readonly visionToken: { readonly start: string; readonly end: string };
  /** Fixed target shape expected by native LLM `[C, H, W]`. */
  readonly targetShape: readonly [number, number, number];
  /** Image preprocessing options (normalization, resize mode, interpolation). */
  readonly preprocessorOpts: ImagePreprocessorOptions;
};

/**
 * Audio preprocessing and sentinel token config for audio-language LLMs.
 * @category Types
 */
export type LLMAudioPreprocessorConfig = {
  /** Sentinel token delimiters inserted into Jinja prompts. */
  readonly audioToken: { readonly start: string; readonly end: string };
};

/**
 * Preprocessor configuration for media modalities.
 * @category Types
 */
export type LLMMediaPreprocessorConfig = {
  readonly image?: LLMImagePreprocessorConfig;
  readonly audio?: LLMAudioPreprocessorConfig;
};

/**
 * Options for instantiating a ChatPreprocessor.
 * @category Types
 */
export type ChatPreprocessorConfig = {
  readonly chatTemplate: string;
  readonly tools?: readonly ToolDefinition[];
  readonly modalities?: readonly Modality[];
  readonly preprocessorConfig?: LLMMediaPreprocessorConfig;
};

/**
 * Chat preprocessor object for Jinja template rendering, prompt diffing, and
 * media tensor preprocessing.
 * @category Types
 */
export type ChatPreprocessor = {
  /**
   * Releases all allocated native tensor resources and the underlying image
   * preprocessor.
   */
  readonly dispose: () => void;

  /**
   * Disposes all active prompt tensors generated by previous preprocessing
   * turns.
   */
  readonly reset: () => void;

  /**
   * Formats the conversation history into a runner-ready {@link Prompt} payload,
   * calculating incremental prompt diffs for multi-turn KV cache prefilling.
   *
   * Depending on `lastKMessages`, it performs the following:
   * - `lastKMessages === history.length`: Renders the entire conversation from
   *   scratch and processes all embedded media.
   * - `lastKMessages === 0`: Extracts only the trailing assistant generation
   *   prompt header (when `addGenPrompt: true`).
   * - `0 < lastKMessages < history.length`: Renders the prefix
   *   `history[:-lastKMessages]` (without generation prompt) and the full
   *   conversation `history`. Validates that the rendered output is strictly
   *   monotonic (the prefix matches the beginning of the full text), then
   *   slices only the newly appended diff for prefilling.
   *
   * Replaces all media placeholders with preprocessed tensors.
   * @param history The complete conversation message history.
   * @param lastKMessages The number of newly added messages at the end of
   * `history` to extract incrementally (`0 <= lastKMessages <= history.length`).
   * @param options Formatting configuration.
   * @param options.addGenPrompt Whether to append the assistant generation
   * header to trigger model completion. Defaults to `true`.
   * @returns The processed {@link Prompt} payload (string or interleaved media
   * array) ready to pass to the LLM runner.
   * @throws {RnExecuTorchError} With code `INVALID_ARGUMENT` if `lastKMessages`
   * is negative or exceeds `history.length`.
   * @throws {RnExecuTorchError} With code `INVALID_STATE` if the model's chat
   * template is non-monotonic, preventing safe incremental KV cache prefilling.
   */
  readonly process: (
    history: readonly ChatMessage[],
    lastKMessages: number,
    options?: { readonly addGenPrompt?: boolean }
  ) => Prompt;

  /**
   * Renders the conversation history into a formatted text string using the
   * Jinja template and collects media items.
   * @param messages Array of chat messages in the conversation.
   * @param options Additional rendering options (e.g. `addGenPrompt`).
   * @returns Object containing the rendered text string and the media map.
   */
  readonly render: (
    messages: readonly ChatMessage[],
    options?: { readonly addGenPrompt?: boolean }
  ) => { text: string; mediaMap: Map<number, ChatMediaInput> };

  /**
   * Replaces media sentinel tokens in rendered text with preprocessed media
   * tensors.
   * @param text Rendered prompt string containing sentinel tokens.
   * @param mediaMap Map of media inputs collected during rendering.
   * @returns Prompt payload ready for runner inference.
   */
  readonly buildPrompt: (text: string, mediaMap: Map<number, ChatMediaInput>) => Prompt;
};

const MEDIA_SENTINEL_PREFIX = '\uFFFC__ET_MEDIA_';
const MEDIA_SENTINEL_REGEX = /\uFFFC__ET_MEDIA_(\d+)__/g;

/**
 * Converts interleaved message content into text containing sentinel media
 * tokens.
 * @param content Chat message text or media input array.
 * @param options Sentinel tokens, supported modalities, and starting media index.
 * @returns Object containing serialized text and a map of media items.
 */
function chatContentToString(
  content?: ChatMessageContent,
  options?: {
    readonly startMediaIdx?: number;
    readonly visionToken?: { readonly start: string; readonly end: string };
    readonly audioToken?: { readonly start: string; readonly end: string };
    readonly modalities?: readonly Modality[];
  }
): { text: string; mediaMap: Map<number, ChatMediaInput> } {
  if (!content) return { text: '', mediaMap: new Map() };
  if (typeof content === 'string') return { text: content, mediaMap: new Map() };

  const mediaMap = new Map<number, ChatMediaInput>();

  let mediaIdx = options?.startMediaIdx ?? 0;
  let text = '';

  for (const item of content) {
    if (typeof item === 'string') {
      text += item;
      continue;
    }

    if (!options?.modalities || !options.modalities.includes(item.kind)) {
      throw RnExecuTorchError('INVALID_ARGUMENT', `${item.kind} is not supported`);
    }

    if (item.kind === 'image') {
      if (!options.visionToken) {
        throw RnExecuTorchError('INVALID_ARGUMENT', "'visionToken' is required for image input");
      }
      const token = options.visionToken;
      text += `${token.start}${MEDIA_SENTINEL_PREFIX}${mediaIdx}__${token.end}`;
      mediaMap.set(mediaIdx, item);
      ++mediaIdx;
    }

    if (item.kind === 'audio') {
      throw RnExecuTorchError('INVALID_ARGUMENT', 'Audio input not yet supported');
    }
  }

  return { text, mediaMap };
}

/**
 * Formats chat messages into string representation for Jinja template
 * rendering.
 * @param messages Array of chat messages.
 * @param options Sentinel tokens and modalities configuration.
 * @returns Object containing formatted string messages and map of media items.
 */
function prepareStringMessages(
  messages: readonly ChatMessage[],
  options?: {
    readonly visionToken?: { readonly start: string; readonly end: string };
    readonly audioToken?: { readonly start: string; readonly end: string };
    readonly modalities?: readonly Modality[];
  }
) {
  const mediaMap = new Map<number, ChatMediaInput>();
  const formattedMessages = [];

  let mediaCounter = 0;

  for (const msg of messages) {
    const opts = { startMediaIdx: mediaCounter, ...options };
    const { text, mediaMap: msgMedia } = chatContentToString(msg.content, opts);

    mediaCounter += msgMedia.size;
    for (const [k, v] of msgMedia) {
      mediaMap.set(k, v);
    }

    let textMsg;
    /* eslint-disable camelcase */
    switch (msg.role) {
      case 'user':
        textMsg = { role: msg.role, content: text };
        break;
      case 'system':
        textMsg = { role: msg.role, content: text };
        break;
      case 'assistant':
        textMsg = { role: msg.role, content: text, tool_calls: msg.toolCalls };
        break;
      case 'tool':
        textMsg = { role: msg.role, content: text, tool_call_id: msg.toolCallId, name: msg.name };
        break;
    }
    /* eslint-enable camelcase */
    formattedMessages.push(textMsg);
  }

  return { messages: formattedMessages, mediaMap };
}

/**
 * Handles Jinja template formatting and media tensor preprocessing for chat
 * turns.
 * @category Typescript API
 * @param config Preprocessor configuration including template and preprocessor
 * settings.
 * @returns A ChatPreprocessor object containing process, render, buildPrompt,
 * reset, and dispose methods.
 */
export function createChatPreprocessor(config: ChatPreprocessorConfig): ChatPreprocessor {
  const { chatTemplate, modalities, preprocessorConfig, tools } = config;
  const template = new Template(chatTemplate);

  let imgPreprocessor: ReturnType<typeof createImagePreprocessor> | undefined;
  let imgShape: [number, number, number] | undefined;

  if (preprocessorConfig?.image !== undefined) {
    imgShape = [...preprocessorConfig.image.targetShape];
    imgPreprocessor = createImagePreprocessor(preprocessorConfig.image.preprocessorOpts, imgShape);
  }

  const tensors: Tensor[] = [];

  const dispose = () => {
    imgPreprocessor?.dispose();
    tensors.forEach((t) => t.dispose());
  };

  const reset = () => {
    tensors.forEach((t) => t.dispose());
    tensors.length = 0;
  };

  const buildPrompt = (text: string, mediaMap: Map<number, ChatMediaInput>): Prompt => {
    if (mediaMap.size === 0 || !text.includes(MEDIA_SENTINEL_PREFIX)) {
      return text;
    }

    const regex = new RegExp(MEDIA_SENTINEL_REGEX.source, 'g');
    const prompt: (string | MediaInput)[] = [];

    let match: RegExpExecArray | null;
    let lastIndex = 0;

    while ((match = regex.exec(text)) !== null) {
      const textChunk = text.slice(lastIndex, match.index);
      if (textChunk.length > 0) prompt.push(textChunk);

      const mediaIdx = parseInt(match[1]!, 10);
      const media = mediaMap.get(mediaIdx);

      if (media?.kind === 'image') {
        if (!imgPreprocessor || !imgShape) {
          throw RnExecuTorchError('INVALID_ARGUMENT', 'Image preprocessor is undefined.');
        }

        const tImage = tensor('float32', imgShape);
        imgPreprocessor.process(media.image).copyTo(tImage);

        prompt.push({ kind: 'image', image: tImage });
        tensors.push(tImage);
      }

      if (media?.kind === 'audio') {
        throw RnExecuTorchError('INVALID_ARGUMENT', 'Audio input not yet supported');
      }

      lastIndex = regex.lastIndex;
    }

    const tail = text.slice(lastIndex);
    if (tail.length > 0) prompt.push(tail);

    return prompt;
  };

  const render = (
    messages: readonly ChatMessage[],
    options?: { readonly addGenPrompt?: boolean }
  ): { text: string; mediaMap: Map<number, ChatMediaInput> } => {
    const addGenPrompt = options?.addGenPrompt ?? true;

    const { messages: stringMessages, mediaMap } = prepareStringMessages(messages, {
      visionToken: preprocessorConfig?.image?.visionToken,
      audioToken: preprocessorConfig?.audio?.audioToken,
      modalities,
    });

    /* eslint-disable camelcase */
    const text = template.render({
      tools: tools?.map((t) => ({ type: t.type, function: t.function })),
      messages: stringMessages,
      add_generation_prompt: addGenPrompt,
    });
    /* eslint-enable camelcase */

    return { text, mediaMap };
  };

  const process = (
    history: readonly ChatMessage[],
    lastKMessages: number,
    options?: { readonly addGenPrompt?: boolean }
  ): Prompt => {
    if (lastKMessages < 0 || lastKMessages > history.length) {
      throw RnExecuTorchError(
        'INVALID_ARGUMENT',
        `lastKMessages must be between 0 and ${history.length}, got ${lastKMessages}`
      );
    }

    if (lastKMessages === history.length) {
      const { text: fullRenderedText, mediaMap } = render(history, options);
      return buildPrompt(fullRenderedText, mediaMap);
    }

    const previous = history.slice(0, history.length - lastKMessages);
    const { text: prevText } = render(previous, { addGenPrompt: false });
    const { text: currText, mediaMap } = render(history, options);

    if (!currText.startsWith(prevText)) {
      throw RnExecuTorchError(
        'INVALID_STATE',
        `Chat template is not monotonic: rendered string for history[:-${lastKMessages}] ` +
          'is not a prefix of the full conversation rendered string.'
      );
    }

    const diffText = currText.slice(prevText.length);
    return buildPrompt(diffText, mediaMap);
  };

  return { dispose, reset, process, render, buildPrompt };
}
