name: Llama Example app Android build check
on:
  pull_request:
    paths:
      - .github/workflows/build-android-llama-example.yml
      - android/**
      - third-party/android/**
      - examples/llama/package.json
      - examples/llama/android/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-android-llama-example.yml
      - android/**
      - third-party/android/**
      - examples/llama/package.json
      - examples/llama/android/**
jobs:
  build:
    if: github.repository == 'software-mansion/react-native-executorch'
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: examples/llama
    concurrency:
      group: android-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Install node dependencies
        run: yarn install --immutable
      - name: Build app
        working-directory: ${{ env.WORKING_DIRECTORY }}/android
        run: ./gradlew assembleDebug --build-cache -PreactNativeArchitectures=arm64-v8a
