name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - docs/**
      - readmes/**
      - "**.md"
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - docs/**
      - readmes/**
      - "**.md"
  merge_group:
    types:
      - checks_requested
  workflow_dispatch:
jobs:
  lint:
    if: github.event.pull_request.draft != true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint files
        run: yarn lint

      - name: Typecheck files
        run: yarn workspaces foreach --all --topological-dev run prepare && yarn typecheck

  build-library:
    if: github.event.pull_request.draft != true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build all packages
        run: yarn workspaces foreach --all --topological-dev run prepare
