import * as d from 'typegpu/data';

export const bubbleSchema = d.struct({
  metersDepth: d.f32,
  stepLength: d.f32,
  varyingStepLength: d.u32,
  dithering: d.u32,
  angleDistortion: d.f32,
  lightAbsorbtion: d.f32,
  colorOne: d.vec3f,
  colorTwo: d.vec3f,
  colorThree: d.vec3f,
  colorFour: d.vec3f,
  colorDensity: d.f32,
  colorMultiplier: d.f32,
  scale: d.f32,
  scaleMultiplier: d.f32,
  factor: d.f32,
  optimisedNoise: d.u32,
  numberOfOctaves: d.u32,
  shiftVector: d.vec3f,
  sphereRadius: d.f32,
  sphereThickness: d.f32,
  sphereNoiseMultiplier: d.f32,
  additionalLayerOfDeformations: d.u32,
  absInFormula: d.u32,
  noiseIsAdded: d.u32,
  addNoiseMultiplier: d.f32,
  volumeMultiplier: d.f32,
});
